// Generated by FIR Compiler
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2004 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.
// 01
// altera message_off 10036
(* altera_attribute = "-name MESSAGE_DISABLE 15400; -name MESSAGE_DISABLE 14130; -name MESSAGE_DISABLE 10036; -name MESSAGE_DISABLE 12020; -name MESSAGE_DISABLE 12030; -name MESSAGE_DISABLE 12010; -name MESSAGE_DISABLE 12110; -name MESSAGE_DISABLE 14320; -name MESSAGE_DISABLE 13410" *)
module lpf_st (clk, 
              rst, 
              data_in, 
              clk_en, 
              done, 
              rdy_to_ld, 
              fir_result ); 

parameter DATA_WIDTH  = 16;
parameter COEF_WIDTH  = 11;
parameter COEF_WIDTH_IN  = 11;
parameter ACCUM_WIDTH = 28;

input clk, rst;
input [DATA_WIDTH -1 :0] data_in;
input clk_en;
output done;
wire done;
wire done_int;
wire data_ld;
output rdy_to_ld;
wire rdy_to_ld;
wire rdy_int;
output [ACCUM_WIDTH-1:0] fir_result;

wire acc_rst_out;
wire coef_in_clk;
assign coef_in_clk = clk;
wire [15:0] tdl_dat_0_n;
wire [15:0] tdl_dat_1_n;
wire [15:0] tdl_dat_2_n;
wire [15:0] tdl_dat_3_n;
wire [15:0] tdl_dat_4_n;
wire [15:0] tdl_dat_5_n;
wire [15:0] tdl_dat_6_n;
wire [15:0] tdl_dat_7_n;
wire [15:0] tdl_dat_8_n;
wire [15:0] tdl_dat_9_n;
wire [15:0] tdl_dat_10_n;
wire [15:0] tdl_dat_11_n;
wire [15:0] tdl_dat_12_n;
wire [15:0] tdl_dat_13_n;
wire [15:0] tdl_dat_14_n;
wire [15:0] tdl_dat_15_n;
wire [15:0] tdl_dat_15_n_pre;
wire [15:0] data_in_dd;
lc_store_cen Udin(.clk(clk), .rst(rst), .ce(rdy_int),.gclk_en(clk_en), .data_in(data_in),.q(data_in_dd) );
defparam Udin.WIDTH = 16;
tdl_da_lc tdl_ff_0_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(data_in_dd),.data_out(tdl_dat_0_n));
defparam tdl_ff_0_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_1_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_0_n),.data_out(tdl_dat_1_n));
defparam tdl_ff_1_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_2_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_1_n),.data_out(tdl_dat_2_n));
defparam tdl_ff_2_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_3_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_2_n),.data_out(tdl_dat_3_n));
defparam tdl_ff_3_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_4_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_3_n),.data_out(tdl_dat_4_n));
defparam tdl_ff_4_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_5_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_4_n),.data_out(tdl_dat_5_n));
defparam tdl_ff_5_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_6_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_5_n),.data_out(tdl_dat_6_n));
defparam tdl_ff_6_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_7_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_6_n),.data_out(tdl_dat_7_n));
defparam tdl_ff_7_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_8_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_7_n),.data_out(tdl_dat_8_n));
defparam tdl_ff_8_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_9_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_8_n),.data_out(tdl_dat_9_n));
defparam tdl_ff_9_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_10_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_9_n),.data_out(tdl_dat_10_n));
defparam tdl_ff_10_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_11_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_10_n),.data_out(tdl_dat_11_n));
defparam tdl_ff_11_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_12_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_11_n),.data_out(tdl_dat_12_n));
defparam tdl_ff_12_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_13_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_12_n),.data_out(tdl_dat_13_n));
defparam tdl_ff_13_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_14_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_13_n),.data_out(tdl_dat_14_n));
defparam tdl_ff_14_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_15_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_14_n),.data_out(tdl_dat_15_n));
defparam tdl_ff_15_ch_0_n.WIDTH = 16;

// symmetrical adders ...
wire [16:0] sym_res_0_n;
sadd_cen U_0_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_0_n), .bin(tdl_dat_15_n), .res(sym_res_0_n) );
defparam U_0_sym_add.IN_WIDTH = 16;
defparam U_0_sym_add.PIPE_DEPTH = 1;
wire [16:0] sym_res_1_n;
sadd_cen U_1_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_1_n), .bin(tdl_dat_14_n), .res(sym_res_1_n) );
defparam U_1_sym_add.IN_WIDTH = 16;
defparam U_1_sym_add.PIPE_DEPTH = 1;
wire [16:0] sym_res_2_n;
sadd_cen U_2_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_2_n), .bin(tdl_dat_13_n), .res(sym_res_2_n) );
defparam U_2_sym_add.IN_WIDTH = 16;
defparam U_2_sym_add.PIPE_DEPTH = 1;
wire [16:0] sym_res_3_n;
sadd_cen U_3_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_3_n), .bin(tdl_dat_12_n), .res(sym_res_3_n) );
defparam U_3_sym_add.IN_WIDTH = 16;
defparam U_3_sym_add.PIPE_DEPTH = 1;
wire [16:0] sym_res_4_n;
sadd_cen U_4_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_4_n), .bin(tdl_dat_11_n), .res(sym_res_4_n) );
defparam U_4_sym_add.IN_WIDTH = 16;
defparam U_4_sym_add.PIPE_DEPTH = 1;
wire [16:0] sym_res_5_n;
sadd_cen U_5_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_5_n), .bin(tdl_dat_10_n), .res(sym_res_5_n) );
defparam U_5_sym_add.IN_WIDTH = 16;
defparam U_5_sym_add.PIPE_DEPTH = 1;
wire [16:0] sym_res_6_n;
sadd_cen U_6_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_6_n), .bin(tdl_dat_9_n), .res(sym_res_6_n) );
defparam U_6_sym_add.IN_WIDTH = 16;
defparam U_6_sym_add.PIPE_DEPTH = 1;
wire [16:0] sym_res_7_n;
sadd_cen U_7_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_7_n), .bin(tdl_dat_8_n), .res(sym_res_7_n) );
defparam U_7_sym_add.IN_WIDTH = 16;
defparam U_7_sym_add.PIPE_DEPTH = 1;


wire coef_en ;
assign coef_en = clk_en;
wire [10:0] coef_st_comb_0_n;
wire [COEF_WIDTH-1:0]coef_st_0_n;
assign coef_st_0_n = coef_st_comb_0_n[10:0];
msft_lt_32 Ucoef_0_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(11'b0), .data_out(coef_st_comb_0_n));
defparam Ucoef_0_n.WIDTH = COEF_WIDTH;
defparam Ucoef_0_n.LENGTH = 1;
defparam Ucoef_0_n.DELAY = 0;
defparam Ucoef_0_n.C0 = 10;
wire [10:0] coef_st_comb_1_n;
wire [COEF_WIDTH-1:0]coef_st_1_n;
assign coef_st_1_n = coef_st_comb_1_n[10:0];
msft_lt_32 Ucoef_1_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(11'b0), .data_out(coef_st_comb_1_n));
defparam Ucoef_1_n.WIDTH = COEF_WIDTH;
defparam Ucoef_1_n.LENGTH = 1;
defparam Ucoef_1_n.DELAY = 0;
defparam Ucoef_1_n.C0 = 38;
wire [10:0] coef_st_comb_2_n;
wire [COEF_WIDTH-1:0]coef_st_2_n;
assign coef_st_2_n = coef_st_comb_2_n[10:0];
msft_lt_32 Ucoef_2_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(11'b0), .data_out(coef_st_comb_2_n));
defparam Ucoef_2_n.WIDTH = COEF_WIDTH;
defparam Ucoef_2_n.LENGTH = 1;
defparam Ucoef_2_n.DELAY = 0;
defparam Ucoef_2_n.C0 = 13;
wire [10:0] coef_st_comb_3_n;
wire [COEF_WIDTH-1:0]coef_st_3_n;
assign coef_st_3_n = coef_st_comb_3_n[10:0];
msft_lt_32 Ucoef_3_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(11'b0), .data_out(coef_st_comb_3_n));
defparam Ucoef_3_n.WIDTH = COEF_WIDTH;
defparam Ucoef_3_n.LENGTH = 1;
defparam Ucoef_3_n.DELAY = 0;
defparam Ucoef_3_n.C0 = 1950;
wire [10:0] coef_st_comb_4_n;
wire [COEF_WIDTH-1:0]coef_st_4_n;
assign coef_st_4_n = coef_st_comb_4_n[10:0];
msft_lt_32 Ucoef_4_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(11'b0), .data_out(coef_st_comb_4_n));
defparam Ucoef_4_n.WIDTH = COEF_WIDTH;
defparam Ucoef_4_n.LENGTH = 1;
defparam Ucoef_4_n.DELAY = 0;
defparam Ucoef_4_n.C0 = 1889;
wire [10:0] coef_st_comb_5_n;
wire [COEF_WIDTH-1:0]coef_st_5_n;
assign coef_st_5_n = coef_st_comb_5_n[10:0];
msft_lt_32 Ucoef_5_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(11'b0), .data_out(coef_st_comb_5_n));
defparam Ucoef_5_n.WIDTH = COEF_WIDTH;
defparam Ucoef_5_n.LENGTH = 1;
defparam Ucoef_5_n.DELAY = 0;
defparam Ucoef_5_n.C0 = 61;
wire [10:0] coef_st_comb_6_n;
wire [COEF_WIDTH-1:0]coef_st_6_n;
assign coef_st_6_n = coef_st_comb_6_n[10:0];
msft_lt_32 Ucoef_6_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(11'b0), .data_out(coef_st_comb_6_n));
defparam Ucoef_6_n.WIDTH = COEF_WIDTH;
defparam Ucoef_6_n.LENGTH = 1;
defparam Ucoef_6_n.DELAY = 0;
defparam Ucoef_6_n.C0 = 572;
wire [10:0] coef_st_comb_7_n;
wire [COEF_WIDTH-1:0]coef_st_7_n;
assign coef_st_7_n = coef_st_comb_7_n[10:0];
msft_lt_32 Ucoef_7_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(11'b0), .data_out(coef_st_comb_7_n));
defparam Ucoef_7_n.WIDTH = COEF_WIDTH;
defparam Ucoef_7_n.LENGTH = 1;
defparam Ucoef_7_n.DELAY = 0;
defparam Ucoef_7_n.C0 = 1023;


wire [27:0] mlu_resx_0_n;
mlu_inf_2reg Umlu_0_n (.clk(clk), .data_in(sym_res_0_n), .coef_in(coef_st_0_n), .clk_en(clk_en), .mlu_out(mlu_resx_0_n) );
defparam Umlu_0_n.DATA_WIDTH = 17;
defparam Umlu_0_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_0_n.PIPE = 2;
defparam Umlu_0_n.DSP_USE = "YES";
wire [27:0] mlu_res_0_n;
mac_tl Umtl_0_n             (.clk(clk), 
             .data_in(mlu_resx_0_n),
             .data_out(mlu_res_0_n));
defparam Umtl_0_n.DATA_WIDTH = 28;

wire [27:0] mlu_resx_1_n;
mlu_inf_2reg Umlu_1_n (.clk(clk), .data_in(sym_res_1_n), .coef_in(coef_st_1_n), .clk_en(clk_en), .mlu_out(mlu_resx_1_n) );
defparam Umlu_1_n.DATA_WIDTH = 17;
defparam Umlu_1_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_1_n.PIPE = 2;
defparam Umlu_1_n.DSP_USE = "YES";
wire [27:0] mlu_res_1_n;
mac_tl Umtl_1_n             (.clk(clk), 
             .data_in(mlu_resx_1_n),
             .data_out(mlu_res_1_n));
defparam Umtl_1_n.DATA_WIDTH = 28;

wire [27:0] mlu_resx_2_n;
mlu_inf_2reg Umlu_2_n (.clk(clk), .data_in(sym_res_2_n), .coef_in(coef_st_2_n), .clk_en(clk_en), .mlu_out(mlu_resx_2_n) );
defparam Umlu_2_n.DATA_WIDTH = 17;
defparam Umlu_2_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_2_n.PIPE = 2;
defparam Umlu_2_n.DSP_USE = "YES";
wire [27:0] mlu_res_2_n;
mac_tl Umtl_2_n             (.clk(clk), 
             .data_in(mlu_resx_2_n),
             .data_out(mlu_res_2_n));
defparam Umtl_2_n.DATA_WIDTH = 28;

wire [27:0] mlu_resx_3_n;
mlu_inf_2reg Umlu_3_n (.clk(clk), .data_in(sym_res_3_n), .coef_in(coef_st_3_n), .clk_en(clk_en), .mlu_out(mlu_resx_3_n) );
defparam Umlu_3_n.DATA_WIDTH = 17;
defparam Umlu_3_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_3_n.PIPE = 2;
defparam Umlu_3_n.DSP_USE = "YES";
wire [27:0] mlu_res_3_n;
mac_tl Umtl_3_n             (.clk(clk), 
             .data_in(mlu_resx_3_n),
             .data_out(mlu_res_3_n));
defparam Umtl_3_n.DATA_WIDTH = 28;

wire [27:0] mlu_resx_4_n;
mlu_inf_2reg Umlu_4_n (.clk(clk), .data_in(sym_res_4_n), .coef_in(coef_st_4_n), .clk_en(clk_en), .mlu_out(mlu_resx_4_n) );
defparam Umlu_4_n.DATA_WIDTH = 17;
defparam Umlu_4_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_4_n.PIPE = 2;
defparam Umlu_4_n.DSP_USE = "YES";
wire [27:0] mlu_res_4_n;
mac_tl Umtl_4_n             (.clk(clk), 
             .data_in(mlu_resx_4_n),
             .data_out(mlu_res_4_n));
defparam Umtl_4_n.DATA_WIDTH = 28;

wire [27:0] mlu_resx_5_n;
mlu_inf_2reg Umlu_5_n (.clk(clk), .data_in(sym_res_5_n), .coef_in(coef_st_5_n), .clk_en(clk_en), .mlu_out(mlu_resx_5_n) );
defparam Umlu_5_n.DATA_WIDTH = 17;
defparam Umlu_5_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_5_n.PIPE = 2;
defparam Umlu_5_n.DSP_USE = "YES";
wire [27:0] mlu_res_5_n;
mac_tl Umtl_5_n             (.clk(clk), 
             .data_in(mlu_resx_5_n),
             .data_out(mlu_res_5_n));
defparam Umtl_5_n.DATA_WIDTH = 28;

wire [27:0] mlu_resx_6_n;
mlu_inf_2reg Umlu_6_n (.clk(clk), .data_in(sym_res_6_n), .coef_in(coef_st_6_n), .clk_en(clk_en), .mlu_out(mlu_resx_6_n) );
defparam Umlu_6_n.DATA_WIDTH = 17;
defparam Umlu_6_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_6_n.PIPE = 2;
defparam Umlu_6_n.DSP_USE = "YES";
wire [27:0] mlu_res_6_n;
mac_tl Umtl_6_n             (.clk(clk), 
             .data_in(mlu_resx_6_n),
             .data_out(mlu_res_6_n));
defparam Umtl_6_n.DATA_WIDTH = 28;

wire [27:0] mlu_resx_7_n;
mlu_inf_2reg Umlu_7_n (.clk(clk), .data_in(sym_res_7_n), .coef_in(coef_st_7_n), .clk_en(clk_en), .mlu_out(mlu_resx_7_n) );
defparam Umlu_7_n.DATA_WIDTH = 17;
defparam Umlu_7_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_7_n.PIPE = 2;
defparam Umlu_7_n.DSP_USE = "YES";
wire [27:0] mlu_res_7_n;
mac_tl Umtl_7_n             (.clk(clk), 
             .data_in(mlu_resx_7_n),
             .data_out(mlu_res_7_n));
defparam Umtl_7_n.DATA_WIDTH = 28;

wire [28:0] tree_l_0_n_0_n;
sadd_c_cen Uaddl_0_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_0_n), .bin(mlu_res_1_n), .res(tree_l_0_n_0_n) );
defparam Uaddl_0_n_0_n.IN_WIDTH = 28;
defparam Uaddl_0_n_0_n.PIPE_DEPTH = 1;
wire [28:0] tree_l_0_n_1_n;
sadd_c_cen Uaddl_0_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_2_n), .bin(mlu_res_3_n), .res(tree_l_0_n_1_n) );
defparam Uaddl_0_n_1_n.IN_WIDTH = 28;
defparam Uaddl_0_n_1_n.PIPE_DEPTH = 1;
wire [28:0] tree_l_0_n_2_n;
sadd_c_cen Uaddl_0_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_4_n), .bin(mlu_res_5_n), .res(tree_l_0_n_2_n) );
defparam Uaddl_0_n_2_n.IN_WIDTH = 28;
defparam Uaddl_0_n_2_n.PIPE_DEPTH = 1;
wire [28:0] tree_l_0_n_3_n;
sadd_c_cen Uaddl_0_n_3_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_6_n), .bin(mlu_res_7_n), .res(tree_l_0_n_3_n) );
defparam Uaddl_0_n_3_n.IN_WIDTH = 28;
defparam Uaddl_0_n_3_n.PIPE_DEPTH = 1;

wire [29:0] tree_l_1_n_0_n;
sadd_cen Uaddl_1_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_0_n), .bin(tree_l_0_n_1_n), .res(tree_l_1_n_0_n) );
defparam Uaddl_1_n_0_n.IN_WIDTH = 29;
defparam Uaddl_1_n_0_n.PIPE_DEPTH = 1;
wire [29:0] tree_l_1_n_1_n;
sadd_cen Uaddl_1_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_2_n), .bin(tree_l_0_n_3_n), .res(tree_l_1_n_1_n) );
defparam Uaddl_1_n_1_n.IN_WIDTH = 29;
defparam Uaddl_1_n_1_n.PIPE_DEPTH = 1;

wire [30:0] tree_l_2_n_0_n;
sadd_reg_top_cen Uaddl_2_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_0_n), .bin(tree_l_1_n_1_n), .res(tree_l_2_n_0_n) );
defparam Uaddl_2_n_0_n.IN_WIDTH = 30;
defparam Uaddl_2_n_0_n.PIPE_DEPTH = 1;

wire [30:0] fir_mc_res;
assign fir_mc_res=tree_l_2_n_0_n;
wire [27:0] fir_temp_res;
assign fir_temp_res = fir_mc_res[ACCUM_WIDTH-1:0];
wire [27:0] fir_int_res;
lc_store_cen Ures_reg (.clk(clk), .ce(done_int), .rst(rst), .gclk_en(clk_en),.data_in(fir_temp_res[ACCUM_WIDTH-1:0]), .q(fir_int_res) );
defparam Ures_reg.WIDTH = ACCUM_WIDTH;
assign fir_result = fir_int_res;
scv_ctrl ctrl(.rst(rst), .clk(clk), .clk_en(clk_en), .done_int(done_int), .rdy_int(rdy_int), .coef_ld(coef_ld), 
.done(done), .data_ld(data_ld), .rdy_to_ld(rdy_to_ld));
defparam ctrl.REG_LEN   = 1;
defparam ctrl.PIPE_DLY  = 8;
defparam ctrl.NO_SYM   = 0; 

endmodule
