// Generated by FIR Compiler
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2004 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.
// 01
// altera message_off 10036
(* altera_attribute = "-name MESSAGE_DISABLE 15400; -name MESSAGE_DISABLE 14130; -name MESSAGE_DISABLE 10036; -name MESSAGE_DISABLE 12020; -name MESSAGE_DISABLE 12030; -name MESSAGE_DISABLE 12010; -name MESSAGE_DISABLE 12110; -name MESSAGE_DISABLE 14320; -name MESSAGE_DISABLE 13410" *)
module hf_6_st (clk, 
              rst, 
              data_in, 
              clk_en, 
              done, 
              rdy_to_ld, 
              fir_result ); 

parameter DATA_WIDTH  = 32;
parameter COEF_WIDTH  = 12;
parameter COEF_WIDTH_IN  = 12;
parameter ACCUM_WIDTH = 46;

input clk, rst;
input [DATA_WIDTH -1 :0] data_in;
input clk_en;
output done;
wire done;
wire done_int;
wire data_ld;
output rdy_to_ld;
wire rdy_to_ld;
wire rdy_int;
output [ACCUM_WIDTH-1:0] fir_result;

wire acc_rst_out;
wire rev_copy;
wire coef_in_clk;
assign coef_in_clk = clk;
wire [31:0] tdl_dat_0_n;
wire [31:0] tdl_dat_1_n;
wire [31:0] tdl_dat_1_n_pre;
wire [31:0] data_in_mux;
wire [31:0] data_rev;
wire [31:0] data_rev_pre;
mux_2to1_cen tdl_mux(.clk(clk), .rst(rst), .gclk_en(clk_en), .bin(tdl_dat_0_n), .ain(data_in),
 .data_out(data_in_mux), .sel(rdy_int));
defparam tdl_mux.IN_WIDTH = 32;
msft_data tdl_ff_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(data_in_mux),.data_out(tdl_dat_0_n));
defparam tdl_ff_0_n.WIDTH = 32;
defparam tdl_ff_0_n.LENGTH = 64;
defparam tdl_ff_0_n.DELAY = 0;
msft_data tdl_ff_1_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(data_rev),.data_out(tdl_dat_1_n));
defparam tdl_ff_1_n.WIDTH = 32;
defparam tdl_ff_1_n.LENGTH = 64;
defparam tdl_ff_1_n.DELAY = 0;
msft_data_reseq tdl_rev(.rst(rst), .clk(clk),.clk_en(clk_en), .we(data_ld), .copy(rev_copy),.data_in(tdl_dat_0_n),.data_out(data_rev_pre));
defparam tdl_rev.WIDTH = 32;
defparam tdl_rev.LENGTH = 64;
defparam tdl_rev.DELAY = 0;
defparam tdl_rev.IS_ODD = 0;
delay_mux tdl_ff_2_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld),.sel(1'b1), .data_in(data_rev_pre),.data_out_delay(data_rev));
defparam tdl_ff_2_n.WIDTH = 32;
defparam tdl_ff_2_n.LENGTH = 1920;

// symmetrical adders ...
wire [32:0] sym_res_0_n;
sadd_cen U_0_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_0_n), .bin(tdl_dat_1_n), .res(sym_res_0_n) );
defparam U_0_sym_add.IN_WIDTH = 32;
defparam U_0_sym_add.PIPE_DEPTH = 1;


wire coef_en ;
assign coef_en = clk_en;
wire [11:0] coef_st_comb_0_n;
wire [COEF_WIDTH-1:0]coef_st_0_n;
assign coef_st_0_n = coef_st_comb_0_n[11:0];
msft_lt_128 Ucoef_0_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(12'b0), .data_out(coef_st_comb_0_n));
defparam Ucoef_0_n.WIDTH = COEF_WIDTH;
defparam Ucoef_0_n.LENGTH = 64;
defparam Ucoef_0_n.DELAY = 0;
defparam Ucoef_0_n.C0 = 4037;
defparam Ucoef_0_n.C1 = 20;
defparam Ucoef_0_n.C2 = 5;
defparam Ucoef_0_n.C3 = 4075;
defparam Ucoef_0_n.C4 = 29;
defparam Ucoef_0_n.C5 = 4066;
defparam Ucoef_0_n.C6 = 27;
defparam Ucoef_0_n.C7 = 4074;
defparam Ucoef_0_n.C8 = 16;
defparam Ucoef_0_n.C9 = 4086;
defparam Ucoef_0_n.C10 = 5;
defparam Ucoef_0_n.C11 = 4095;
defparam Ucoef_0_n.C12 = 0;
defparam Ucoef_0_n.C13 = 1;
defparam Ucoef_0_n.C14 = 4095;
defparam Ucoef_0_n.C15 = 1;
defparam Ucoef_0_n.C16 = 0;
defparam Ucoef_0_n.C17 = 0;
defparam Ucoef_0_n.C18 = 0;
defparam Ucoef_0_n.C19 = 0;
defparam Ucoef_0_n.C20 = 0;
defparam Ucoef_0_n.C21 = 0;
defparam Ucoef_0_n.C22 = 0;
defparam Ucoef_0_n.C23 = 0;
defparam Ucoef_0_n.C24 = 0;
defparam Ucoef_0_n.C25 = 0;
defparam Ucoef_0_n.C26 = 0;
defparam Ucoef_0_n.C27 = 2047;
defparam Ucoef_0_n.C28 = 3857;
defparam Ucoef_0_n.C29 = 26;
defparam Ucoef_0_n.C30 = 53;
defparam Ucoef_0_n.C31 = 4009;
defparam Ucoef_0_n.C32 = 97;
defparam Ucoef_0_n.C33 = 4004;
defparam Ucoef_0_n.C34 = 79;
defparam Ucoef_0_n.C35 = 4035;
defparam Ucoef_0_n.C36 = 43;
defparam Ucoef_0_n.C37 = 4070;
defparam Ucoef_0_n.C38 = 12;
defparam Ucoef_0_n.C39 = 4094;
defparam Ucoef_0_n.C40 = 4092;
defparam Ucoef_0_n.C41 = 7;
defparam Ucoef_0_n.C42 = 4088;
defparam Ucoef_0_n.C43 = 7;
defparam Ucoef_0_n.C44 = 4090;
defparam Ucoef_0_n.C45 = 4;
defparam Ucoef_0_n.C46 = 4094;
defparam Ucoef_0_n.C47 = 1;
defparam Ucoef_0_n.C48 = 0;
defparam Ucoef_0_n.C49 = 0;
defparam Ucoef_0_n.C50 = 0;
defparam Ucoef_0_n.C51 = 0;
defparam Ucoef_0_n.C52 = 0;
defparam Ucoef_0_n.C53 = 0;
defparam Ucoef_0_n.C54 = 0;
defparam Ucoef_0_n.C55 = 0;
defparam Ucoef_0_n.C56 = 0;
defparam Ucoef_0_n.C57 = 0;
defparam Ucoef_0_n.C58 = 0;
defparam Ucoef_0_n.C59 = 893;
defparam Ucoef_0_n.C60 = 3666;
defparam Ucoef_0_n.C61 = 273;
defparam Ucoef_0_n.C62 = 3918;
defparam Ucoef_0_n.C63 = 110;


wire [44:0] mlu_resx_0_n;
mlu_nd Umlu_0_n (.clk(clk), .data_in(sym_res_0_n), .coef_in(coef_st_0_n), .clk_en(clk_en), .mlu_out(mlu_resx_0_n) );
defparam Umlu_0_n.DATA_WIDTH = 33;
defparam Umlu_0_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_0_n.PIPE = 3;
defparam Umlu_0_n.DSP_USE = "YES";
wire [44:0] mlu_res_0_n;
mac_tl Umtl_0_n             (.clk(clk), 
             .data_in(mlu_resx_0_n),
             .data_out(mlu_res_0_n));
defparam Umtl_0_n.DATA_WIDTH = 45;

wire [45:0] tree_l_0_n_0_n;
sadd_reg_top_cen Uaddl_0_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_0_n), .bin(45'd0), .res(tree_l_0_n_0_n) );
defparam Uaddl_0_n_0_n.IN_WIDTH = 45;
defparam Uaddl_0_n_0_n.PIPE_DEPTH = 1;

wire [45:0] fir_mc_res;
assign fir_mc_res=tree_l_0_n_0_n;
wire [45:0] fir_acc_in;
wire [45:0] fir_temp_res;
wire [45:0] fir_acc_in_reg;
assign fir_acc_in = fir_mc_res[ACCUM_WIDTH-1:0];
lc_store_cen Uaccum_reg (.clk(clk), .ce(1'b1), .gclk_en(clk_en),.rst(rst), .data_in(fir_acc_in), .q(fir_acc_in_reg) );
defparam Uaccum_reg.WIDTH = ACCUM_WIDTH;
maccum_cen Usa (.clk(clk), .gclk_en(clk_en),.rst(acc_rst_out), .ain(fir_acc_in_reg), .accum_out(fir_temp_res));
defparam Usa.WIDTH_A = ACCUM_WIDTH;
wire [45:0] fir_int_res;
lc_store_cen Ures_reg (.clk(clk), .ce(done_int), .rst(rst), .gclk_en(clk_en),.data_in(fir_temp_res[ACCUM_WIDTH-1:0]), .q(fir_int_res) );
defparam Ures_reg.WIDTH = ACCUM_WIDTH;
assign fir_result = fir_int_res;
mcv_ctrl_deci ctrl
(.rst(rst), .clk(clk), .acc_rst_out(acc_rst_out),.clk_en(clk_en), 
.done_int(done_int), .rdy_int(rdy_int), .rev_copy(rev_copy), .data_ld(data_ld), .done(done), .rdy_to_ld(rdy_to_ld));
defparam ctrl.REG_LEN   = 32;
defparam ctrl.DECI_FACT   = 2;
defparam ctrl.DECI_WIDTH   = 1;
defparam ctrl.PIPE_DLY  = 73;
defparam ctrl.PIPE_WIDTH  = 7;
defparam ctrl.IS_ODD  = 0;
defparam ctrl.IS_SYM  = 1;
defparam ctrl.SINGLE_COEF_SET  = 1;

endmodule
